/**
 * @file MCT8316Z_pwm.c
 * @brief PWM control functions for the MCT8316Z motor controller.
 *
 * This module provides runtime control of the PWM signal used by the
 * MCT8316Z motor controller. The PWM output is generated by the Silicon Labs
 * PWM driver instance sl_pwm_Motor.
 *
 * The PWM frequency is changed by deinitializing and reinitializing the PWM
 * peripheral because the Silicon Labs PWM driver does not provide a direct
 * runtime frequency-update function. The current duty cycle is preserved
 * during frequency changes.
 *
 * The PWM duty cycle can be changed while the PWM peripheral is running.
 *
 * @note The PWM output is briefly disabled while its frequency is changed.
 * @note PWM frequency values must be greater than zero and within the
 *       supported TIMER peripheral range.
 *
 * @see sl_pwm_Motor
 */
#include "sl_pwm.h"
#include "sl_pwm_instances.h"
#include "sl_pwm_init_pwm1_config.h"


static struct motor {
  uint32_t pwm_frequency;
  uint8_t  pwm_duty_cycle;
} motor = {
  .pwm_frequency = SL_PWM_PWM1_FREQUENCY,
  .pwm_duty_cycle = 0
};


 /**
 * @brief Set the PWM output frequency.
 *
 * Saves the current duty cycle, reinitializes the PWM peripheral with the
 * requested frequency, restores the saved duty cycle, and restarts the PWM
 * output.
 *
 * @param[in] frequency_hz PWM frequency in hertz.
 *
 * @note The PWM output is temporarily disabled during reinitialization.
 * @note If PWM initialization fails, the output remains disabled.
 * @note The caller must not pass a frequency of zero.
 */
 
/**
 * @brief Set the PWM output frequency.
 *
 * Saves the current duty cycle, reinitializes the PWM peripheral with the
 * requested frequency, restores the saved duty cycle, and restarts the PWM
 * output.
 *
 * @param[in] frequency_hz PWM frequency in hertz.
 *
 * @note The PWM output is temporarily disabled during reinitialization.
 * @note If PWM initialization fails, the output remains disabled.
 * @note The caller must not pass a frequency of zero.
 */
void MCT8316Z_set_frequency(uint32_t frequency_hz)
{
  if(frequency_hz == 0) {
    // Invalid frequency, do not change PWM settings
    return;
  }

  motor.pwm_frequency = frequency_hz; // not returned by pwm driver.

  uint8_t duty = sl_pwm_get_duty_cycle(&sl_pwm_Motor);

  // Changin frequency requires reinit of pwm peripheral
  sl_pwm_deinit(&sl_pwm_Motor);  // no support to change after instantiation

  sl_pwm_config_t config = {
    .frequency = frequency_hz,
    .polarity = PWM_ACTIVE_HIGH
  };

  if (sl_pwm_init(&sl_pwm_Motor, &config) == SL_STATUS_OK) 
  {
    sl_pwm_set_duty_cycle(&sl_pwm_Motor, duty);
    sl_pwm_start(&sl_pwm_Motor);
  }
}

uint32_t MCT8316Z_get_frequency(void) 
{
    return motor.pwm_frequency;
};



uint8_t  MCT8316Z_get_duty(void)
{
  return sl_pwm_get_duty_cycle(&sl_pwm_Motor);
};

/**
 * @brief Set the PWM output duty cycle.
 *
 * Updates the percentage of each PWM period for which the output remains
 * active. The PWM peripheral remains running while the duty cycle is updated.
 *
 * @param[in] percent Duty cycle percentage in the range 0 to 100.
 *
 * @note A value of 0 produces 0% duty cycle.
 * @note A value of 100 produces 100% duty cycle.
 */
void MCT8316Z_set_duty ( uint8_t duty)
{
	  if (duty > 100) {
    return;
  }

	  sl_pwm_set_duty_cycle(&sl_pwm_Motor, duty);
    motor.pwm_duty_cycle = duty;
}

